globalmangrovewatch/gmw-users

- mrtt-ui/package-lock.json
- mrtt-ui/package.json
- same as description (in addition to updating test script to run jest)
Fixes #4 
- create a basic function in .js file
- create a matching test.js file
- `npm run test`
I followed [this example ](https://jestjs.io/docs/getting-started)to see that Jest is running with `npm run test`.
1) Add basic sum function in sum.js file
2) add corresponding sum.test.js file
3) `npm run test`
> [4] Add jest and react testing lib to dev dependencies

- .github/workflows/heroku-review-app.yaml
Added GH workflow for creating review apps in Heroku.
Fixes #3 
1. Create a PR
2. GH Action should trigger creation of review apps
3. A new comment will be added indicating the URL of the review app
> Added GH workflow for creating review apps

- .github/workflows/heroku-review-app.yaml
Pushing new code to the same PR creates another app. Delete the old one first.
Fixes #3 
> Delete old review app 

- .github/workflows/heroku-review-app.yaml
Pass GH repo secrets as Heroku config vars.
Fixes #35
Review app created should have config vars set under `Settings > Config vars`.
> Set Heroku config vars

- .gitignore
- .husky/pre-commit
- .husky/pre-push
- .npmrc
- mrtt-ui/.npmrc
- mrtt-ui/.prettierrc
- mrtt-ui/package-lock.json
- mrtt-ui/package.json
- mrtt-ui/src/App.test.js
- mrtt-ui/src/index.css
- package-lock.json
- package.json
- lock down node version to avoid weird bugs
- install git hooks (via Husky) at the repo root so that it runs
Fixes # 33
1. change some files and commit them, see prettier run
2. push changes to remote repo. Watch lint and tests run.
Manually. See instructions.
> 33 fix git hooks

- mrtt-ui/src/data/questions.js
central questions file to build off of
> Chore: Add questions object to store questions and options all in one place

- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/CheckboxGroup/CheckboxGroup.js
- mrtt-ui/src/components/CheckboxGroup/CheckboxGroup.stories.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsCheckboxGroupWithLabel.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js
- mrtt-ui/src/components/RestorationAimsForm/StakeholderBenefitsInputs.js
- mrtt-ui/src/components/SiteBackgroundForm.js
- mrtt-ui/src/data/questions.js
- mrtt-ui/src/language.js
- mrtt-ui/src/library/strings/makeValidClassName.js
- mrtt-ui/src/library/useInitializeQuestionMappedForm.js
- mrtt-ui/src/styles/forms.js
- mrtt-ui/src/validation/multiSelectWithOther.js
- incorporate question 3.4 into 3.1, 3.2, 3.3
- modify causes of decline form to use MUI FormControlLabel and to avoid common component in `forms.js` to be confused with other used in nested questions
- make sure when user unselects parent checkbox, nested values clear
- loads all values from api
- validations still works
- no format change for CheckboxGroup (like previous WIP contained)
Fixes #72
> Feature/72 question3.4 

- mrtt-ui/src/App.js
> [124] feat: route root url to sites list page

- mrtt-ui/src/App.js
- mrtt-ui/src/views/Auth/SignupForm.js
A rudimentary signup page.
Things to figure out:
- How to navigate into the page (Link from a login form?)
- How to navigate out of the page (where to land after a successful signup?)
> Sign up page

- mrtt-ui/src/components/GlobalLayout.js
- mrtt-ui/src/components/Header/Header.js
- mrtt-ui/src/components/Header/HeaderMenu.js
- mrtt-ui/src/language.js
- mrtt-ui/src/styles/containers.js
- mrtt-ui/src/styles/theme.js
Closes #99 
Ignored Desktop user menu icon change for Desktop.
> [99] feat: Header

- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
updated `causesOfDeclineTypesChecked` and `stakeholderTypesChecked` from `causesOfDeclineTypesIsChecked` and `stakeholderTypesIsChecked`
this way we don't think the types array is a boolean 👍
> Form section 2 & 4: fix isChecked var names to better naming strategy

- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/CheckboxGroupWithLabelAndController.js
- mrtt-ui/src/components/GlobalLayout.js
- mrtt-ui/src/components/Header/Header.js
- mrtt-ui/src/components/MobileFooter/MobileFooter.js
- mrtt-ui/src/components/ProjectDetailsForm.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsCheckboxGroupWithLabel.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
- mrtt-ui/src/styles/forms.js
- mrtt-ui/src/styles/theme.js
- mrtt-ui/src/styles/themeMui.js
- mrtt-ui/src/views/SiteForm.js
> initial sticky headers, other minor layout & UI stuff

- .github/workflows/heroku-review-app.yaml
Adds `REACT_APP_AUTH_URL` to review app.
Any new review app should have `REACT_APP_AUTH_URL` configured.
> Fix env var for review app

- mrtt-ui/src/components/Header/HeaderMenu.js
- mrtt-ui/src/components/MobileFooter/MobileFooter.js
- mrtt-ui/src/index.css
- mrtt-ui/src/styles/buttons.js
- mrtt-ui/src/styles/containers.js
- mrtt-ui/src/styles/theme.js
- mrtt-ui/src/styles/themeMui.js
- mrtt-ui/src/styles/typography.js
- mrtt-ui/src/views/Landscapes.js
- mrtt-ui/src/views/Organizations.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
- mrtt-ui/src/views/Sites.js
Made the cards a bit nicer, sill going to account for devices without a hover state later on.
Lots of typography stuff, generalized some typography components and fixed header hierarchy.
> Card styles, typography, other minor ui stuff

- mrtt-ui/src/components/ProjectAreaMap.js
- mrtt-ui/src/styles/forms.js
put the z-index on the map, not the question
> put the z-index on the map, not the question

- mrtt-ui/src/language.js
- mrtt-ui/src/views/LandscapeForm.js
Make org required for landscape form submit
closes #179
> [179] feat: make org required for landscape create/edit form

- mrtt-ui/src/App.js
- mrtt-ui/src/components/SiteInterventions.js
- mrtt-ui/src/data/questionMapping.js
- mrtt-ui/src/data/questions.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
- Section 6 form excluding 6.2a/b/c/d (tabular input + complex questions)
- Added 6.1, 6.2, 6.3, 6.3a, and 6.4 (multiselect or drop down select)
- Does API call and loads data after submitting form
- 6.3a only appears if 6.3 is 'Yes'
1. Go to Site Interventions Form
2.  Click through sections
3. Submit
4. Reload to make sure data is saved
> Section 6 Form: non-complex questions

- mrtt-ui/src/components/PreRestorationAssessmentForm.js
Fixes [issue 221](https://github.com/globalmangrovewatch/gmw-users/issues/221)
Simple text updates to include measurement types in property
> [CHORE] Section 5: add text updates to specify measurement types

- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/data/questions.js
[bug ticket here](https://github.com/globalmangrovewatch/gmw-users/issues/248)
> remove two extra fields from funder names in 7.3

- .github/workflows/heroku-review-app.yaml
Set stack to heroku-20
Should resolve #256 
Create PR going to `develop`.
> Set stack to heroku-20

- mrtt-ui/src/App.js
- mrtt-ui/src/language.js
- mrtt-ui/src/styles/typography.js
- mrtt-ui/src/views/ManageOrganizationUsers.js
- mrtt-ui/src/views/NewOrganizationUser.js
Description:
new org user form
Test:
- sign in as user2@example.com
- click orgs list
- click Manage Users button for Organization AAA
- click New User button
- add nonsense email: should get validation message saying user doesnt exist
- add user3@example.com: see success toast
- click cancel or back to users link. Note new user in users table
> feat: new org user form (set base to develop prior to merge)

- mrtt-ui/src/App.js
- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/components/ManagementStatusAndEffectiveness/ManagementStatusAndEffectivenessForm.js
- mrtt-ui/src/constants/sectionNames.js
- mrtt-ui/src/data/questionMapping.js
- mrtt-ui/src/data/questions.js
- mrtt-ui/src/language.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
- Pretty straight forward section - no tabular inputs
- Some logic with yes/no questions and other sections appearing
- Should be tested by going through sections, answering questions, refreshing, etc
> Section 8: Management Status and Effectiveness Form

- .github/workflows/heroku-review-app.yaml
Doesn't fix but relates to issue #14 
FE code should be updated to consume env var.
> Added transifex key (#14)

- mrtt-ui/src/components/CausesOfDeclineForm.js
Issue: [Cause of decline validation dead end #270](https://github.com/globalmangrovewatch/gmw-users/issues/270)
> Bug fix: Causes of decline - remove min requirement for causes of decline

- mrtt-ui/src/components/ManagementStatusAndEffectiveness/ManagementStatusAndEffectivenessForm.js
- mrtt-ui/src/components/PreRestorationAssessment/PreRestorationAssessmentForm.js
- mrtt-ui/src/components/SiteInterventions/SiteInterventions.js
- mrtt-ui/src/data/questionMapping.js
- mrtt-ui/src/data/questions.js
- remove start/end date for each item in 6.2
- add start end date for all items in 6.2 in 6.2a
- includes logic so that 6.2a does not appear if 'None' is selected in 6.2
> Update 6.2 to remove start/end date for each item

- mrtt-ui/src/components/Costs/ProjectFunderNamesRow.js
- mrtt-ui/src/components/PreRestorationAssessment/PhysicalMeasurementRow.js
- mrtt-ui/src/components/SiteInterventions/MangroveAssociatedSpeciesRow.js
- mrtt-ui/src/language.js
- mrtt-ui/src/views/LandscapeForm.js
- mrtt-ui/src/views/ManageOrganizationUsers.js
- Add 'are you sure you want to delete this row' to tabular input groups in Costs, Pre-restoration Assessment, and Site Interventions
- Using ConfirmPrompt (yay thanks for making this @mmnoo )
> Feature: tabular delete check for input rows

- mrtt-ui/src/App.js
- mrtt-ui/src/components/ManagementStatusAndEffectiveness/ManagementStatusAndEffectivenessForm.js
- mrtt-ui/src/components/SocioeconomicAndGovernance/SocioeconomicAndGovernanceStatusAndOutcomes.js
- mrtt-ui/src/components/SocioeconomicAndGovernance/SocioeconomicAndGovernanceStatusAndOutcomesForm.js
- mrtt-ui/src/constants/sectionNames.js
- mrtt-ui/src/data/questionMapping.js
- mrtt-ui/src/data/questions.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
- All sections excluding tabular input (9.4). Will create a separate pr for this section
-  Bug fix for section 8 where page was crashing due to typo in questions file
> Feature/section9: Socioeconomic Governance and Status Outcomes

- mrtt-ui/src/App.js
- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
- mrtt-ui/src/constants/sectionNames.js
- mrtt-ui/src/data/questionMapping.js
- mrtt-ui/src/data/questions.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
Section 10 excluding two tabular input questions (10.3a & 10.7)
Some questions (10.6 & 10.6a) only appear if 'Planting' is selected in 6.2, Site Interventions.
To test:
- go to section 6, then select and save 'Planting' in 6.2
- go to section 10 and view 10.6 &. 10.6a
- try adding & different selection in section 10
> Feature/section10 : non-complex questions

- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
- mrtt-ui/src/components/ManagementStatusAndEffectiveness/ManagementStatusAndEffectivenessForm.js
- mrtt-ui/src/components/PreRestorationAssessment/PreRestorationAssessmentForm.js
- mrtt-ui/src/components/ProjectDetailsForm.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
- mrtt-ui/src/components/SiteInterventions/SiteInterventions.js
- mrtt-ui/src/components/SocioeconomicAndGovernance/SocioeconomicAndGovernanceStatusAndOutcomesForm.js
update `registration_answers` to `registration_intervention_answers`
> Update registration answers route across all forms

- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
- mrtt-ui/src/data/questionMapping.js
- mrtt-ui/src/data/questions.js
ended up being more simple than a tabular input question
just added one question for 4 text inputs within it since it is just one row
> Question 10.4a

- mrtt-ui/src/components/SocioeconomicAndGovernance/SocioeconomicAndGovernanceStatusAndOutcomesForm.js
- mrtt-ui/src/components/SocioeconomicAndGovernance/socioeconomicOutcomesRow.js
9.4a link outcome to aims is now a checkbox group instead of a single select option
To test
1. create a new site
2. go to section 3
3. add aims in 3.2
4. go to section 9
5. check items in 9.4
6. scroll to 9.4a
7. check linked outcomes
8. save & refresh
> Feature: 9.4a multiselect

- mrtt-ui/src/views/Auth/SignupForm.js
- go to sign up form
- fill out form
- notice submit button text changes to '...submitting' after it is pressed.
> fix: [308] make sign up submit button show submitting text when operation in progress

- mrtt-ui/package-lock.json
- mrtt-ui/package.json
- mrtt-ui/src/language.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
- pick a site and go to its site overview
- scroll to the bottom and click the Download Site Data button
- see the download in the browser. The file name should match the site name.
- open the downloaded file in a text editor, see the json.
> feat: [276] site data download button

- mrtt-ui/src/components/QuestionNav.js
to test:
- go to any form section
- shrink browser size to mobile
- see sticky question nav
> Add sticky question nav header on mobile

- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
- mrtt-ui/src/components/ProjectDetailsForm.js
- mrtt-ui/src/components/SiteInterventions/SiteInterventionsForm.js
- fixes validation in 1c, 10.2 and 6.2a
> Prevent end date being before start date

- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
- mrtt-ui/src/data/questions.js
mis-numbered previously - 10.3a was showing as 10.4a (which should not exist)
> update question order for 10.3a and 10.4

- mrtt-ui/README.md
- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/data/causesOfDeclineOptions.js
- text edits for causes of decline
- added error text incase there are any errors for level of degradation drop down select
> causes of decline edits

- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
Adds the dropdown with "All Data" and "Public Data" options to the Site `Download Report` button.
Explain what someone needs to do in order to test the functionality of the changes.
> Add "Add Data" and "Public Data" Options to Site Download Report Button

- mrtt-ui/src/components/CheckboxGroupWithLabelAndController.js
- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
- mrtt-ui/src/components/ManagementStatusAndEffectiveness/ManagementStatusAndEffectivenessForm.js
- mrtt-ui/src/components/PreRestorationAssessment/PreRestorationAssessmentForm.js
- mrtt-ui/src/components/SiteInterventions/SiteInterventionsForm.js
- mrtt-ui/src/components/SocioeconomicAndGovernance/SocioeconomicAndGovernanceStatusAndOutcomesForm.js
> Answers fix required

- mrtt-ui/src/components/EcologicalStatusAndOutcomes/EcologicalStatusAndOutcomesForm.js
> nest RequiredIndicator like 8.1 and 9.1

- mrtt-ui/src/language.js
- mrtt-ui/src/views/Auth/SignupForm.js
- Clean up console.logs
- Update validation error copy
- Update terms and conditions copy
Manual testing
> Update Validation and Checkbox Wording and Clean up Code

- mrtt-ui/src/language.js
- mrtt-ui/src/views/Auth/SignupForm.js
Revert the terms and conditions copy to previous.
Manual testing
> Revert Terms and Conditions Link Copy

- mrtt-ui/package.json
- mrtt-ui/pnpm-lock.yaml
- mrtt-ui/src/components/Header/HeaderMenu.js
- mrtt-ui/src/components/contact/index.jsx
- mrtt-ui/src/hooks/contact.tsx
- mrtt-ui/tsconfig.json
> contact form

- mrtt-ui/public/index.html
- mrtt-ui/src/components/Header/HeaderMenu.js
- mrtt-ui/src/components/about/index.jsx
- mrtt-ui/src/components/contact/styles.js
- mrtt-ui/src/components/landing/header-desktop.jsx
- mrtt-ui/src/components/landing/header-mobile.jsx
- mrtt-ui/src/components/landing/styles.js
- mrtt-ui/src/styles/v2/containers/landing.js
- mrtt-ui/src/views/Auth/LoginForm.js
> header fix

- mrtt-ui/src/components/Header/HeaderMenu.js
- mrtt-ui/src/components/Header/styles.js
- mrtt-ui/src/components/contact/styles.js
- mrtt-ui/src/components/landing/header-desktop.jsx
- mrtt-ui/src/components/landing/header.jsx
- mrtt-ui/src/components/landing/styles.js
- mrtt-ui/src/styles/v2/containers/landing.js
- mrtt-ui/src/views/Auth/LoginForm.js
> login header

- mrtt-ui/src/views/Auth/LoginForm.js
This pull request updates the `LoginForm` component in `mrtt-ui` to enhance functionality and improve user experience by adding an external link and refining imports. Below are the most significant changes:
* Added an external link to the MRTT guide in the `HeroText` section, allowing users to access more information. The link opens in a new tab and uses the `ExternalLink` component with styling for better visibility.
* Updated imports in `LoginForm.js` to include the `Link` component as `ExternalLink` from `../../styles/typography`, enabling the addition of the external link.
* Enhanced the `useMediaQuery` import to include `fontWeight` from `@mui/system`, preparing for potential styling improvements.
> learn more link
