- mrtt-ui/src/components/ButtonSubmit.js
- mrtt-ui/src/language.js
- mrtt-ui/src/styles/forms.js
- mrtt-ui/src/styles/typography.js
Reusable components to unblock Julia/Melissa syncing
- SectionFormTitle
- ErrorText
- ButtonSubmit
- Form - styled to make sure error text wasnt inline with submit button
> Reusable components

- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js
- mrtt-ui/src/language.js
- mrtt-ui/src/validation/multiSelectWithOther.js
I took your `aimsValidation` and made it into a more generic `multiselectWithOtherValidation`. Didn't change any functionality, mostly just renamed a few things. Now we can re-used this in any form with `multiselectWithOther `question type.
Fixes # [FEATURE] [Create reusable validation for multiple choice with other validation](https://github.com/globalmangrovewatch/gmw-users/issues/66)
> create generic validation for multiselect with other

- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
- mrtt-ui/src/data/questions.js
Previously, when you would refresh, checked items would not appear after submitting answers for 2.1. This fixes the issue.
I added a new array for useState that always have up to date stakeholderTypes (string values, not the whole object). 
This is a more performance optimized version (as opposed to searching through an array of objects every time). Performance optimization will be much more noticeable in section 4 (the heavily nested section) when the same pattern is used .
Fixes # (missing issue, but similar to [4.2 bug](https://github.com/globalmangrovewatch/gmw-users/issues/93))
1. Go to section 2 (Site Background Form)
2. Submit answers (particularly for 2.1)
3. Refresh
4. Answers should be checked in 2.1
> Bug Fix for 2.1 : checked items now appear after submit + refresh

- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
Fixes bug where checked items were not showing as checked upon initial load (when previous answers exist). 
I added an array which makes managing checked items easier to manage. When an item is checked/unchecked, a ``${label}-${answer}`` gets added or removed from the array. This is way less complicated than filtering through deeply nested items, and much less computationally expensive.
[Fixes # (93)](https://github.com/globalmangrovewatch/gmw-users/issues/93)
1. Go to section 4
2.  Check items in 4.2
3. Submit 
4. Refresh to see checked items are still there
> [BUG FIX] Section 4 form - update checked items to display correctly in 4.2 upon initial load

- mrtt-ui/src/App.js
- mrtt-ui/src/components/SubmitErrorWithExtraErrorContent.js
- mrtt-ui/src/language.js
- mrtt-ui/src/styles/containers.js
- mrtt-ui/src/views/LandscapeForm.js
- mrtt-ui/src/views/Landscapes.js
- mrtt-ui/src/views/SiteForm.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
- mrtt-ui/src/views/Sites.js
- create a landscape
- edit a landscape
Editing:
- click new landscape button on landscape list page
- enter stuff in form
- click submit/cancel
Creating new landscape:
- click 'Edit' link in landscape 'card' on landscape list page
- enter stuff in form
- click submit/cancel
I noticed that the api wont let you use the same landscape name twice. There is no code other than 422 which feels fairly generic to filter on for specific user messaging, so the code is patching the server error message through to the error toast. (for now?). Made a tech debt ticket for it https://github.com/globalmangrovewatch/gmw-users/issues/167
> [148] create and edit a landscape

- mrtt-ui/src/components/ButtonSecondaryWithLoader.js
- mrtt-ui/src/language.js
- mrtt-ui/src/views/LandscapeForm.js
closes #148 
delete a landscape
Details:
- if there are associated sites, some explainer test shows, and the button is disabled
- if there are no associated sites, some different text shows, and the button is enabled
- a generic button was made to show what ever 'holding'/progress text while an operation is in progress.
> [148] feat delete a landscape if no associated sites. (edit base to develop before merge)

- mrtt-ui/src/components/ConfirmPrompt/ConfirmPrompt.js
- mrtt-ui/src/components/ConfirmPrompt/ConfirmPrompt.stories.js
- mrtt-ui/src/language.js
- mrtt-ui/src/styles/typography.js
- mrtt-ui/src/views/LandscapeForm.js
closes #180
instructions:
go to landscape form with no sites (maybe create new one for that), click delete button, see prompt, click cancel, click delete again, click 'yes, delete' button.
> [180] feat: generic ConfirmPrompt component for reuse, using a confim prompt for landscape delete

- mrtt-ui/src/App.js
- mrtt-ui/src/components/ButtonSave.js
- mrtt-ui/src/components/CausesOfDeclineForm.js
- mrtt-ui/src/components/PreRestorationAssessmentForm.js
- mrtt-ui/src/components/ProjectDetailsForm.js
- mrtt-ui/src/components/QuestionNav.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
- mrtt-ui/src/components/SiteInterventions.js
- mrtt-ui/src/language.js
- mrtt-ui/src/library/useSiteInfo.js
- mrtt-ui/src/styles/forms.js
- mrtt-ui/src/styles/typography.js
- mrtt-ui/src/views/CostsForm.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
Closes #143 
Instructions: 
- Click on any section of the form. Use the form nav buttons to move to adjacent forms or back to site overview. Use save button to save the form (moved to top of form, removed submit button)
- Notice that when on the first of last form, the next and previous buttons disable when appropriate
Note that privacy functionality is WIP. That needs some schema/ backend thinking through, so will be another ticket
> [143] feat: questions section navigation (privacy still WIP)

- mrtt-ui/src/components/PreRestorationAssessmentForm.js
Updated validation schema for speciesComposition to fix bad null input.
Fixes # [(192)](https://github.com/globalmangrovewatch/gmw-users/issues/192)
Testing
- create a new site
- go to section 1, add a country to ensure species get pulled in section 5
- go to section 5
- scroll to 5.3f
- add number inputs
- refresh page
- number inputs should still be there (they weren't saving before)
> Bug fix for 5.3f : fix bad input

- mrtt-ui/src/components/ProjectDetailsForm.js
- mrtt-ui/src/data/questions.js
Fixes chore issue [#217](https://github.com/globalmangrovewatch/gmw-users/issues/217)
Order is now:
1. start date
2. does this project have an end date?
3. end date (if yes)
> [CHORE] - Section 1: rearrange question date order

- mrtt-ui/src/components/PreRestorationAssessmentForm.js
- mrtt-ui/src/data/mangroveSpeciesPerCountry.js
Fixes [issue 220](https://github.com/globalmangrovewatch/gmw-users/issues/220) and [219](https://github.com/globalmangrovewatch/gmw-users/issues/219)
- data clean up. Find all periods in species list and replace with a space
- italicize list
- update logic to show country specific species first, followed by the remaining possible species (while removing duplicates)
> Section 5: Data clean up: remove periods from species list and display all species in 5.3e

- mrtt-ui/src/views/Sites.js
- If site has no last_updated_date from server, dont show in UI
- Sort sites by last updated date. New sites with no date show at top, then most recently updated
Decision context:
The api sends null for last updated date when a user newly created a site.  Ideally the BE deals with this brand new site initial date, but an exception was made here. 
The front end has no way of sending the api the right last updated date upon creating a new site, and we are running out of BE dev time, so I opted to just not show the last updated date if none of the questions have been answered (what informs the last updated date in the BE I believe).
> [210] fix: sort sites by questions last answered date. If no questions answered yet, dont show last updated info.

- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/components/Costs/PercentageSplitOfActivitiesRow.js
- mrtt-ui/src/components/PreRestorationAssessment/PhysicalMeasurementRow.js
- mrtt-ui/src/components/SiteInterventions/MangroveAssociatedSpeciesRow.js
- mrtt-ui/src/styles/forms.js
- functionality for 7.5a
- added some style adjustments for tabular row sections, however they are still very inconsistent. I [created a task for this](https://github.com/globalmangrovewatch/gmw-users/issues/239)
to test:
1. create a new site
2. go to section 6
3. select & save items in 6.2 & 6.4 (will be used in 7.5a)
4. go to Costs section
5. Select 'Monetary' in 7.1
6. go to 7.5a
7. add percentages + save & refresh
> 7.5a + some tabular styling updates

- mrtt-ui/public/index.html
This results in a non-working select element appearing in the bottom left of the page. I think a translator and admin need to configure some things and add translations in a Transifex dashboard before we will see actual translation.
> chore: add transifex script

- mrtt-ui/src/components/SiteInterventions/AddMangroveAssociatedSpeciesRow.js
- mrtt-ui/src/components/SiteInterventions/SiteInterventions.js
- mrtt-ui/src/data/questions.js
**6.2b: add multiselect for seedlings and propagule sources**
to test: 
1. Go to section 1 and add a country
2. go back to section 6
3. go to 6.2a > select planting in order for 6.2b to appear
4. select an item from 6.2b
5. select more than one source item from propapagule or seedling drop down
6. save and refresh
note: this is a deeply nested item that doesn't have the best UI. Could use some design improvements but for now I think it works
**6.2c and 6.3d minor text updates**
also, there is a warning that is generated that I am aware of . I don't have a fix for it and will make a separate task to address it. It doesn't affect the functionality of section 6, so not a critical item.
> Section 6 adjustments

- mrtt-ui/src/components/SiteInterventions/SiteInterventions.js
- restructure 6.1 completely from using grouped checked items to fields array with object properties
- when an item is checked, a select box appears with two options: paid or voluntary
to test, check items in 6.1, use select dropdown, refresh
> Feature update: restructure 6.1 to have checked items + select drop down

- mrtt-ui/src/views/SiteQuestionsOverview/AddMonitoringSectionMenu.js
- mrtt-ui/src/views/SiteQuestionsOverview/SiteQuestionsOverview.js
To test:
does section summary page match mockups in terms of groupings?
> fix: [294] section summary groupings

- mrtt-ui/src/App.js
- mrtt-ui/src/language.js
- mrtt-ui/src/views/Auth/LoginForm.js
- mrtt-ui/src/views/Auth/SignupForm.js
after a suer signs up successfully, they will see a toast  and message on the login page they are navigated to saying to check their email. 
to test:
- go to the sign up page
- sign up
- see the toast and message on the login page when redirected
> feat: [245] Update user signup success and error messages

- mrtt-ui/src/language.js
- mrtt-ui/src/views/Auth/SignupForm.js
add  a password confirm input to user sign up form
To test:
- Fill out the form, make the passwords not match. See the validation
- make sure existing validation works (use not an email string, short password)
- use unused email address and fill out form correctly to see it submit
> feat: [237] password confirmation on sign up page

- mrtt-ui/src/App.js
- mrtt-ui/src/language.js
- mrtt-ui/src/views/Auth/ForgotPasswordForm.js
- mrtt-ui/src/views/Auth/LoginForm.js
- mrtt-ui/src/views/Auth/ResetPasswordForm.js
2 Pages:
- forgot password
- reset password
closes # (246)
How to test:
- click the forgot password link on the sign in page
Forgot Password Page:
- leave the email input in the reset password form blank. Hit submit. There should be a validation message saying the input is required.
- fill out the reset password form with something that is not an email. Click submit. There should be a validation message blocking submit.
- fill out the reset password form with an email you actually have access too and have signed up to MRTT with. Click submit
- The app should show a toast saying stuff about checking your email.
Reset Password Page:
- click the link in the email. It will link to a url to a served app somewhere. Change the base url to your localhost in the url bar. 
- click the submit button …
> feat: [237] forgot password and reset password workflow

- mrtt-ui/src/App.js
- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js
- mrtt-ui/src/components/SocioeconomicAndGovernance/SocioeconomicOutcomesRow.js
- mrtt-ui/src/language.js
- mrtt-ui/src/views/Auth/LoginForm.js
- package-lock.json
To test:
- Create a new site. 
- Go to Restoration Aims. Note each question has blue alert text.
- Go to Costs form. Check monetary in 7.1. Scroll to 7.5a. Note the blue alert text.
- Go to Socioeconomic ... form , check something in 9.4. Note blue alert text in 9.4a
> feat: [274] add info/warning text for questions the rely on the answers to other form's questions

- mrtt-ui/src/views/LandscapeForm.js
**To test:**
- sign in, go to create new landscape form
- look at the dropdown for orgs and note which ones are listed. For user 2, it looks like this:
Go to the organizations list page. The orgs under 'Your organizations' should be the same orgs.
You can also check the edit landscape form.
In development I also tested this by conolse-ing out all orgs and making sure the ones with the role of `org-admin` and `org-user` showed up in the org drop down in the landscape form. Not suggesting that for QA, just mentioning it FYI.
> feat: [320] only let a user add orgs to a landscape when they 'belong to the org

- mrtt-ui/src/language.js
- mrtt-ui/src/views/NewOrganizationUser.js
**To Test: ** 
- go to new org user form (organizations, manage users, new user). User2 will have orgs they can manage
- make up an email that definitely isnt registeres and enter it
- click submit
- if working, there should be error text under the input saying that user isnt registered.
Also the text under role instructs that an unregistered user cant be added.
> feat: [318] update new org user error and page text.

- mrtt-ui/src/App.js
- mrtt-ui/src/components/Costs/CostsForm.js
- mrtt-ui/src/components/PreRestorationAssessment/PhysicalMeasurementRow.js
- mrtt-ui/src/components/PreRestorationAssessment/PreRestorationAssessmentForm.js
- mrtt-ui/src/components/SiteBackgroundForm.js
- mrtt-ui/src/components/SiteInterventions/SiteInterventionsForm.js
- mrtt-ui/src/library/organizeMangroveSpeciesList.js
**Changes based on feedback:**
Q2.5 Is marked as mandatory in the tool but shouldn’t be
-  removed required indicator
Q5.3f Percentages shouldn’t be able to total more than 100%
- There is now error text that appears if percentages equal more than 100%
- Setting a custom error for a fields array (instead of individual field items) with react hook form ended up being more complex than expected. For now, users can still submit answers that equal more than 100%, but a warning also displays
Q5.3g Can the table rows be orientated horizontally
- set horizontal rows since there are only two row items, still mobile friendly
Q6.2b Can the species be organized as in Q5.3e (in case people plant non-native species or our species ranges are wrong)
- added `organizeMangroveSpeciesList` to library
Q6.3 …
> Chore: feedback cleanup

- mrtt-ui/src/components/SiteBackgroundForm.js
- go to question 2.1
- select any option other than 'Unknown'. You should see a 'Name' input below the checkbox
- select 'Unknown'. You should not see a name
> fix: [299] dont show name input for question 2.1 when 'Unknown' selected

- mrtt-ui/src/components/FormValidationMessageIfErrors.js
I added an additional toast warning that appears when a user hits save and there are form errors.
There already is a 'this form was not saved' box that sits at the top of the page, however it is easy to miss if you are scrolled past it. I thought about making it sticky, but think the extra toast warning should help
To test:
1. create a new site
2. go to a form page that has required items (such as a monitoring form)
3. hit save without entering any data
4. toast warning should appear
> show toast warning when form is saved with errors

- mrtt-ui/src/language.js
- mrtt-ui/src/views/Landscapes.js
- mrtt-ui/src/views/Organizations.js
- mrtt-ui/src/views/Sites.js
- Removes `Download Data` button from `Landscapes` page
- Connect `Download Data` button to API call on `Organizations` and `Sites` pages
- Browse to `Organizations` page and click on the `Download Data` Button.
- Choose either `Public Only` or `All Data`
- Confirm that excel file downloads with the expected data
- Do the same on the `Sites` page
- Manually on my local environment pointing to staging backend.
> Add Download Data Buttons for Excel Exports
